//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pointage.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cart_items
    {
        public int cart_items_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<int> coupon_id { get; set; }
        [Display(Name ="Quantity")]
        public Nullable<int> product_qty { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual product product { get; set; }
        public virtual coupon coupon { get; set; }
      
    }
}
