//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pointage.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkout
    {
        public int checkout_id { get; set; }
        public Nullable<int> cart_id { get; set; }
        public Nullable<int> coupon_id { get; set; }
        public Nullable<decimal> total_price { get; set; }
        public Nullable<System.DateTime> checkout_date { get; set; }
        public Nullable<System.DateTime> delivery_date { get; set; }
        public string payment_method { get; set; }
    
        public virtual cart cart { get; set; }
        public virtual coupon coupon { get; set; }
    }
}
