//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pointage.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class coupon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public coupon()
        {
            this.cart_items = new HashSet<cart_items>();
            this.checkout = new HashSet<checkout>();
        }

        [Display(Name = "Coupon ID")]
        public int coupon_id { get; set; }
        [Display(Name = "Events")]
        [Required]
        public Nullable<int> event_id { get; set; }
        [Display(Name = "Coupon Name")]
        [Required]
        public string coupon_name { get; set; }
        [Display(Name = "Discount")]
        [DisplayFormat(DataFormatString = "{0:P0}")]
        [Required]
        public Nullable<decimal> discount_val { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_items> cart_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<checkout> checkout { get; set; }
        public virtual events events { get; set; }
    }
}
