//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pointage.Model
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.cart_items = new HashSet<cart_items>();
        }

        [Display(Name = "Product ID")]
        [Required]
        public int product_id { get; set; }
        [Display(Name = "Product Name")]
        [Required]
        public string product_name { get; set; }
        [Display(Name = "Category")]
        [Required]
        public string category_id { get; set; }
        [Display(Name = "Price")]
        [Required]
        public Nullable<decimal> product_price { get; set; }
        [Display(Name = "Availabe Quantity")]
        [Required]
        public Nullable<int> product_available_qty { get; set; }
        [Display(Name = "Image")]
        //[Required]
        public string product_image { get; set; }
        //[Required(ErrorMessage = "Please Select Image")]
        public HttpPostedFileBase ImageFile { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cart_items> cart_items { get; set; }
        public virtual category category { get; set; }
    }
}
